### ISSUE TITLE
Enhancement: Test case preconditions

### ISSUE THREAD

**Issue by bradyaturner** [sonjaq/Test-Outline-to-TestLink-Converter#2]
It would be helpful to have the ability to specify preconditions for a test case. I have found your script very helpful, and may try to implement this myself, if you are interested, I can send you a pull request when I'm finished.

**Comment by sonjaq** [comment]
Feel free to send a pull request on this.  I think adding support for that shouldn't be too difficult.

**Comment by bradyaturner** [comment]
Submitted a pull request.
