### ISSUE TITLE
HTML in expected results

### ISSUE THREAD

**Issue by bradyaturner** [sonjaq/Test-Outline-to-TestLink-Converter#3]
I'm having trouble getting html to work in the expected results. When I import to test link, I get the html tags printed in plain text.

Is there some trick to this I'm missing? I tried bold, paragraph, and unordered list tags and none worked. I also tried wrapping the whole thing inside html tags, but still no luck.

**Comment by sonjaq** [comment]
Can you provide a sample file?  Also, what version of Testlink are you using?

Thanks,

Andrew

**Comment by bradyaturner** [comment]
Hi Andrew,

We are using TestLink 1.9.4. I'll paste a sample file and a screenshot of the test case in TestLink.

Thanks,
Brady

```
{ Top Level Test Suite
+ Test Case Name
  Summary line1
  "Continued Summary"
  More Summary
  ~ Preconditions 1
  ~ Preconditions 2
  ~ Preconditions 3
    - Test Step 1
      = <b>Expected 1</b>
    - Test Step 2
      = <p>Expected 2</p><p>Expected 2.2</p>
}
```

![screen shot 2013-05-10 at 5 05 53 pm](https://f.cloud.github.com/assets/1758004/490285/9b422dce-b9b5-11e2-92e8-509a17b49bdf.png)

**Comment by sonjaq** [comment]
Fixed.

**Comment by bradyaturner** [comment]
Tested your fix, seems to be working, if you want to merge.

**Comment by sonjaq** [comment]
I thought I had done that, my apologies.  This has been done now.
