### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by lullabelle** [sonjaq/Test-Outline-to-TestLink-Converter#7]
Hi

I realise this isn't really an issue but more of a question. Can you tell me how I can insert line breaks into test steps (lines beginning with -) or expected results (lines beginning with =).
I have read some forum answers and they have suggested using the </br> tag but this just prints out in my test cases.
Many thanks

**Comment by sonjaq** [comment]
Hello @lullabelle - 

Currently, this does not support line breaks in tests, but I'll see if I can correct that.

Thanks for pinging us!

**Comment by sonjaq** [comment]
@lullabelle - I'm sorry, but, this isn't going as easy as I expected. This script, we no longer use in house, as TestLink is no longer where we keep out test cases. Feel free to fork and make changes as you see fit! Also, this code is some of my very first PHP and, to be honest, could be a lot cleaner.
